# ai api request & prompt
ai:
  api:
    key: up_KMDrSqMiDBpOC1rw25dG476vqpIpO
    url: https://api.upstage.ai/v1/chat/completions

    prompt:
      system: |
        당신은 URL를 분석하여 피싱 위험도를 판단하는 사이버 보안 전문가입니다.
        주어진 텍스트를 분석하여 (0, 25, 50, 75, 100) 중 하나로 위험도를 판단하세요.
        분석 기준:
        
        의심스러운 URL

        당신의 응답은 오직 (0, 25, 50, 75, 100) 중 하나여야 합니다.
        어떠한 설명이나 추가 텍스트도 절대 포함하지 마세요.
      user: |
        아래 URL를 분석하고 피싱 위험도 점수를 [숫자만] 반환해 주세요.
        
        [분석할 URL]
        %s